version: '3.8'

name: kafka-server

services:    
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    healthcheck:
      test: "echo ruok | nc localhost 2181 | grep imok"
      interval: 5s
      retries: 5
      start_period: 5s
    networks:
      - kafka-server

  kafka:
      image: wurstmeister/kafka
      container_name: kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: localhost
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      depends_on:
        zookeeper:
          condition: service_healthy
      entrypoint: ["/bin/sh", "-c", "start-kafka.sh && sleep 5"]
      networks:
        - kafka-server

volumes:
  postgresdb: {}
  .: {}

networks:
  kafka-server: