name: kafka-server

services:    
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    healthcheck:
      test: "echo ruok | nc localhost 2181 | grep imok"
      interval: 5s
      retries: 5
      start_period: 5s
    networks:
      - kafka-server

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      zookeeper:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c", "start-kafka.sh && sleep 5"]
    networks:
      - kafka-server
  
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - kafka
    command: ["npm", "run", "start:prod"]
    networks:
      - kafka-server

  auth:
    container_name: auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - kafka
    command: ["npm", "run", "start:prod"]
    networks:
      - kafka-server

  billing:
    container_name: billing
    build:
      context: ./billing
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - kafka
    command: ["npm", "run", "start:prod"]
    networks:
      - kafka-server

networks:
  kafka-server: